const c_projects = [
  {
    "id": "kansai-airport-1988",
    "title": "Kansai Airport",
    "type": "Building",
    "year": 1988,
    "designer": "Renzo Piano",
    "location": "Osaka, Japan",
    "lat": 34.432,
    "lng": 135.2304,
    "url": "",
    "image": ""
  },
  {
    "id": "jean-marie-tjibaou-cultural-center-1998",
    "title": "Jean-Marie Tjibaou Cultural Center",
    "type": "Building",
    "year": 1998,
    "designer": "Renzo Piano",
    "location": "Noumea / New Caledonia",
    "lat": -22.2557,
    "lng": 166.4878,
    "url": "",
    "image": ""
  },
  {
    "id": "cern-science-gateway-building-2003",
    "title": "Cern Science Gateway Building",
    "type": "Building",
    "year": 2003,
    "designer": "Renzo Piano",
    "location": "Geneva / Switzerland",
    "lat": 46.2339,
    "lng": 6.0545,
    "url": "",
    "image": ""
  },
  {
    "id": "padre-pio-pilgrimage-church-2004",
    "title": "Padre Pio Pilgrimage Church",
    "type": "Building",
    "year": 2004,
    "designer": "Renzo Piano",
    "location": "San Giovanni Rotondo / Italy",
    "lat": 41.7046,
    "lng": 15.7227,
    "url": "",
    "image": ""
  },
  {
    "id": "california-academy-of-science-2008",
    "title": "California Academy of Science",
    "type": "Building",
    "year": 2008,
    "designer": "Renzo Piano",
    "location": "San Francisco, CA, USA",
    "lat": 37.7699,
    "lng": -122.4661,
    "url": "",
    "image": ""
  },
  {
    "id": "parc-de-la-villette-1998",
    "title": "Parc de la Villette",
    "type": "Building",
    "year": 1998,
    "designer": "Bernard Tschumi",
    "location": "Paris, France",
    "lat": 48.8938,
    "lng": 2.3908,
    "url": "https://www.tschumi.com/projects/3",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGt-TRZTPbRD6WDS5Riqzq2YQf0iOF26J-GFMpBQ8Uog&s=10"
  },
  {
    "id": "le-fresnoy-art-center-1997",
    "title": "Le Fresnoy Art Center",
    "type": "Building",
    "year": 1997,
    "designer": "Bernard Tschumi",
    "location": "Tourcoing, France",
    "lat": 50.7172,
    "lng": 3.159,
    "url": "https://www.tschumi.com/projects/14",
    "image": "https://www.tschumi.com/img/assets/1a63652b-5f46-47f9-b304-c90185df8823?width=700&fit=contain"
  },
  {
    "id": "international-terminal-waterloo-1998",
    "title": "International Terminal Waterloo",
    "type": "Building",
    "year": 1998,
    "designer": "Nicholas Grimshaw",
    "location": "London, UK",
    "lat": 51.5031,
    "lng": -0.1132,
    "url": "",
    "image": ""
  },
  {
    "id": "santa-caterina-market-2005",
    "title": "Santa Caterina Market",
    "type": "Building",
    "year": 2005,
    "designer": "Enric Miralles",
    "location": "Barcelona, Spain",
    "lat": 41.3862,
    "lng": 2.179,
    "url": "https://www.mirallestagliabue.com/project/santa-caterina-market-renovation/",
    "image": "https://www.mirallestagliabue.com/wp-content/uploads/2018/01/SANTA-CATERINA-%C2%A9-ROLAND-HALBE.jpg"
  },
  {
    "id": "city-hall-and-social-center-of-hostalets-2005",
    "title": "City Hall and Social Center of Hostalets",
    "type": "Building",
    "year": 2005,
    "designer": "Enric Miralles",
    "location": "Barcelona, Spain",
    "lat": 41.832,
    "lng": 2.217,
    "url": "https://cpinos.com/en/porfolio/civic-center/",
    "image": "https://arquitecturaviva.com/assets/uploads/obras/58169/av_imagen.webp?h=25536006"
  },
  {
    "id": "ufa-cinema-center-1998",
    "title": "UFA Cinema Center",
    "type": "Building",
    "year": 1998,
    "designer": "Coop Himmelb(l)au",
    "location": "Dresden, Germany",
    "lat": 51.0529,
    "lng": 13.7355,
    "url": "https://coop-himmelblau.at/projects/ufa-cinema-center/",
    "image": "https://coop-himmelblau.at/site/assets/files/4797/chbl-ufa-cinema-center-dresden-germany-duccio-malagamba-02.1200x0.jpg?6241b49a"
  },
  {
    "id": "akron-art-museum-2007",
    "title": "Akron Art Museum",
    "type": "Building",
    "year": 2007,
    "designer": "Coop Himmelb(l)au",
    "location": "Akron, OH, USA",
    "lat": 41.0833,
    "lng": -81.5208,
    "url": "https://coop-himmelblau.at/projects/akron-art-museum/",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIMt-OgL8fsFuIT9ghD8w8UdC9kmnXdDkuKrrAALgVFCyFLu0XmusZog&s=10"
  },
  {
    "id": "rooftop-remodeling-falkestrasse-1988",
    "title": "Rooftop Remodeling Falkestrasse",
    "type": "Building",
    "year": 1988,
    "designer": "Coop Himmelb(l)au",
    "location": "Vienna, Austria",
    "lat": 48.2089,
    "lng": 16.3799,
    "url": "https://coop-himmelblau.at/projects/falkestrasse/",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfqjWsI0VmPDWuOp4V-IwFe7VkJJcMYDv1A_JJIQPzmA&s=10"
  },
  {
    "id": "everything-is-already-an-image-2017",
    "title": "Everything Is Already an Image",
    "type": "Writing",
    "year": 2017,
    "designer": "John May",
    "location": "",
    "url": "",
    "image": ""
  },
  {
    "id": "signal-image-architecture-2019",
    "title": "Signal. Image. Architecture",
    "type": "Writing",
    "year": 2019,
    "designer": "John May",
    "location": "",
    "url": "",
    "image": ""
  },
  {
    "id": "seattle-public-library-2004",
    "title": "Seattle Public Library",
    "type": "Building",
    "year": 2004,
    "designer": "OMA / AMO",
    "location": "Seattle, WA, USA",
    "lat": 47.6067,
    "lng": -122.3325,
    "url": "",
    "image": ""
  },
  {
    "id": "iit-campus-center-2003",
    "title": "IIT Campus Center",
    "type": "Building",
    "year": 2003,
    "designer": "OMA / AMO",
    "location": "Chicago, IL, USA",
    "lat": 41.8348,
    "lng": -87.6262,
    "url": "https://www.oma.com/projects/iit-mccormick-tribune-campus-center",
    "image": "https://cdn.sanity.io/images/5azy6oei/production/f2f8f9c5bf18dd0f93a6c1e7177ff6e32da43f56-3008x2000.tif?w=700&fm=jpg&q=80"
  },
  {
    "id": "de-young-museum-2005",
    "title": "De Young Museum",
    "type": "Building",
    "year": 2005,
    "designer": "Herzog & de Meuron",
    "location": "San Francisco, CA, USA",
    "lat": 37.7715,
    "lng": -122.4687,
    "url": "https://www.herzogdemeuron.com/projects/173-de-young-museum/",
    "image": "https://picturepark.cdn.herzogdemeuron.com/v/98As2gHw/"
  },
  {
    "id": "media-ict-2005",
    "title": "Media-ICT",
    "type": "Building",
    "year": 2005,
    "designer": "Cloud 9 / Enric Ruiz Geli",
    "location": "Barcelona, Spain",
    "lat": 41.4067,
    "lng": 2.1957,
    "url": "https://divisare.com/projects/194744-cloud-9-enric-ruiz-geli-media-ict",
    "image": "https://www.designboom.com/wp-content/uploads/2014/06/02Media-ICT_cloud9.jpg"
  },
  {
    "id": "amant-2021",
    "title": "Amant",
    "type": "Building",
    "year": 2021,
    "designer": "So-IL",
    "location": "New York, NY, USA",
    "lat": 40.7108,
    "lng": -73.9405,
    "url": "https://solidobjectives.com/work/amant/",
    "image": ""
  },
  {
    "id": "breath",
    "title": "Breath",
    "type": "Building",
    "year": 2017,
    "designer": "So-IL",
    "location": "Milan, Italy",
    "lat": 45.4642,
    "lng": 9.19,
    "url": "https://solidobjectives.com/work/breathe/",
    "image": "https://images.ctfassets.net/6v3ra0uy9tu9/1wpAMASyKhjXeicC5VxvgH/301251f0eaa08a54e95c3f24ae9b18d8/copyright_laurianghinitoiu_miniliving_SO-IL__6_of_15_.jpg?w=1920&h=1280&q=100&fm=webp"
  },
  {
    "id": "hunters-point-library-2019",
    "title": "Hunters Point Library",
    "type": "Building",
    "year": 2019,
    "designer": "Steven Holl",
    "location": "New York, NY, USA",
    "lat": 40.744,
    "lng": -73.9578,
    "url": "",
    "image": ""
  },
  {
    "id": "the-nature-and-art-of-workmanship-1971",
    "title": "The Nature and Art of Workmanship",
    "type": "Writing",
    "year": 1971,
    "designer": "David Pye",
    "location": "",
    "url": "https://memoof.me/read/884/pdf",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0vLDssOaBbs7qgd1i2vAox-CBqm8PkgEnbgHYRuVhUA&s=10"
  },
  {
    "id": "witch-trials-memorial-2011",
    "title": "Witch Trials Memorial",
    "type": "Building",
    "year": 2011,
    "designer": "Peter Zumthor",
    "location": "Vardø, Norway",
    "lat": 70.3706,
    "lng": 31.1095,
    "url": "",
    "image": ""
  },
  {
    "id": "swiss-sound-pavilion-2000",
    "title": "Swiss Sound Pavilion",
    "type": "Building",
    "year": 2000,
    "designer": "Peter Zumthor",
    "location": "Hannover, Germany",
    "lat": 52.3225,
    "lng": 9.81,
    "url": "",
    "image": ""
  },
  {
    "id": "ucca-clay-museum-2024",
    "title": "UCCA Clay Museum",
    "type": "Building",
    "year": 2024,
    "designer": "Kengo Kuma",
    "location": "Jiangsu, China",
    "lat": 31.3406,
    "lng": 119.8232,
    "url": "",
    "image": ""
  },
  {
    "id": "centre-pompidou-metz-2010",
    "title": "Centre Pompidou Metz",
    "type": "Building",
    "year": 2010,
    "designer": "Shigeru Ban",
    "location": "France",
    "lat": 49.1076,
    "lng": 6.1819,
    "url": "",
    "image": ""
  },
  {
    "id": "cardboard-cathedral-2013",
    "title": "Cardboard Cathedral",
    "type": "Building",
    "year": 2013,
    "designer": "Shigeru Ban",
    "location": "Christchurch, New Zealand",
    "lat": -43.5334,
    "lng": 172.642,
    "url": "",
    "image": ""
  },
  {
    "id": "house-gables-2018",
    "title": "House Gables",
    "type": "Building",
    "year": 2018,
    "designer": "Jennifer Bonner",
    "location": "Atlanta, GA, USA",
    "lat": 33.749,
    "lng": -84.388,
    "url": "https://jenniferbonner.com/01-Haus-Gables",
    "image": "https://freight.cargo.site/w/750/i/e2f5a53fcec6fef14704774cd8e8eaea3fd5dd67eae2ea66b879d4bea901f5bd/HausGables_MALL_NAARO_21.jpg"
  },
  {
    "id": "plasencia-auditorium-and-congress-center-2017",
    "title": "Plasencia Auditorium and Congress Center",
    "type": "Building",
    "year": 2017,
    "designer": "SelgasCano",
    "location": "Plasencia, Spain",
    "lat": 40.0316,
    "lng": -6.0933,
    "url": "",
    "image": ""
  },
  {
    "id": "harbin-opera-house",
    "title": "Harbin Opera House",
    "type": "Building",
    "year": null,
    "designer": "MAD",
    "location": "Harbin, China",
    "lat": 45.805,
    "lng": 126.57,
    "url": "",
    "image": ""
  },
  {
    "id": "shenzhen-bay-culture-park-2026",
    "title": "Shenzhen Bay Culture Park",
    "type": "Building",
    "year": 2026,
    "designer": "MAD",
    "location": "Shenzhen, China",
    "lat": 22.519,
    "lng": 113.947,
    "url": "",
    "image": ""
  },
  {
    "id": "clemson-college-of-architecture-2012",
    "title": "Clemson College of Architecture",
    "type": "Building",
    "year": 2012,
    "designer": "Thomas Phifer",
    "location": "Clemson, SC, USA",
    "lat": 34.678,
    "lng": -82.837,
    "url": "",
    "image": ""
  },
  {
    "id": "department-of-islamic-arts-2012",
    "title": "Department of Islamic Arts",
    "type": "Building",
    "year": 2012,
    "designer": "Mario Bellini",
    "location": "Paris, France",
    "lat": 48.8606,
    "lng": 2.3376,
    "url": "",
    "image": ""
  },
  {
    "id": "vitra-fire-station-1993",
    "title": "Vitra Fire Station",
    "type": "Building",
    "year": 1993,
    "designer": "Zaha Hadid",
    "location": "Weil am Rhein, Germany",
    "lat": 47.5973,
    "lng": 7.6165,
    "url": "",
    "image": ""
  },
  {
    "id": "walt-disney-concert-hall-2003",
    "title": "Walt Disney Concert Hall",
    "type": "Building",
    "year": 2003,
    "designer": "Frank Gehry",
    "location": "Los Angeles, CA, USA",
    "lat": 34.0553,
    "lng": -118.2498,
    "url": "https://gehry.getty.edu/",
    "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2e/Image-Disney_Concert_Hall_by_Carol_Highsmith_edit.jpg/250px-Image-Disney_Concert_Hall_by_Carol_Highsmith_edit.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail"
  },
  {
    "id": "salk-institute-1966",
    "title": "Salk Institute",
    "type": "Building",
    "year": 1966,
    "designer": "Louis Kahn",
    "location": "La Jolla, CA, USA",
    "lat": 32.8875,
    "lng": -117.243,
    "url": "",
    "image": ""
  },
  {
    "id": "unicorn-farm-1905",
    "title": "Unicorn Farm",
    "type": "Building",
    "year": 1985,
    "designer": "Joseph Henry Wyeth",
    "location": "Idaho, USA",
    "lat": 44.07,
    "lng": -114.74,
    "url": "",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv7-WG-9g8MVN_9pcUwrPhM9FXMf_CCRj4SMPVEUH_1Mx_uVf9bxRu2en2&s=10"
  },
  {
    "id": "cooper-union-2009",
    "title": "Cooper Union",
    "type": "Building",
    "year": 2009,
    "designer": "Morphosis",
    "location": "New York, NY, USA",
    "lat": 40.7289,
    "lng": -73.9907,
    "url": "",
    "image": ""
  },
  {
    "id": "diamond-ranch-high-school-1999",
    "title": "Diamond Ranch High School",
    "type": "Building",
    "year": 1999,
    "designer": "Morphosis",
    "location": "Pomona, CA, USA",
    "lat": 34.0017,
    "lng": -117.7942,
    "url": "",
    "image": ""
  },
  {
    "id": "waffle-2016",
    "title": "Waffle",
    "type": "Building",
    "year": 2016,
    "designer": "Eric Owen Moss",
    "location": "Culver City, CA, USA",
    "lat": 34.0211,
    "lng": -118.3965,
    "url": "https://ericowenmoss.com/project-detail/vespertine/",
    "image": "https://images.adsttc.com/media/images/5f84/763e/63c0/1777/3a00/00b2/large_jpg/Waffle__Culver_City__LA__(c)_EOMA_(2).jpg?1602516512"
  },
  {
    "id": "vagelos-education-center-2016",
    "title": "Vagelos Education Center",
    "type": "Building",
    "year": 2016,
    "designer": "Diller, Scofidio + Renfro",
    "location": "New York, NY, USA",
    "lat": 40.8412,
    "lng": -73.9423,
    "url": "https://dsrny.com/project/roy-and-diana-vagelos-education-center?index=false&section=projects&search=Vagelos%20Education%20Center&tags=education",
    "image": "https://cdn.sanity.io/images/q2tdbkqz/production/8ddb512f6357880ce7fb0b28a02b89e003564cd3-4000x6000.jpg?w=1500&fit=max"
  },
  {
    "id": "slow-house-project-1989",
    "title": "Slow House Project",
    "type": "Building",
    "year": 1989,
    "designer": "Diller, Scofidio + Renfro",
    "location": "North Haven, NY, USA",
    "lat": 41.0043,
    "lng": -72.3047,
    "url": "https://dsrny.com/project/slow-house",
    "image": "https://cdn.sanity.io/images/q2tdbkqz/production/cb800502184b6c41dcdae4889c08b0d058886e4c-6208x6510.jpg?w=1500&fit=max"
  },
  {
    "id": "the-shed-2019",
    "title": "The Shed",
    "type": "Building",
    "year": 2019,
    "designer": "Diller, Scofidio + Renfro",
    "location": "New York, NY, USA",
    "lat": 40.7537,
    "lng": -74.002,
    "url": "https://dsrny.com/project/the-shed",
    "image": "https://cdn.sanity.io/images/q2tdbkqz/production/7b437948ecbf90dbbd0d951bc86d0b888c9f28d7-5769x3900.png?w=2000&fit=max&q=90"
  },
  {
    "id": "the-broad-2015",
    "title": "The Broad",
    "type": "Building",
    "year": 2015,
    "designer": "Diller, Scofidio + Renfro",
    "location": "Los Angeles, CA, USA",
    "lat": 34.0544,
    "lng": -118.2506,
    "url": "https://dsrny.com/project/the-broad?index=false&section=projects&search=the%20broad",
    "image": "https://cdn.sanity.io/images/q2tdbkqz/production/Z4l4OSDiH7TpcuKS4TSzHKAk-6000x4000.jpg?w=2000&fit=max&q=90"
  },
  {
    "id": "lincoln-center-cafe",
    "title": "Lincoln Center Cafe",
    "type": "Building",
    "year": null,
    "designer": "Diller, Scofidio + Renfro",
    "location": "New York, NY, USA",
    "lat": 40.7725,
    "lng": -73.9835,
    "url": "https://dsrny.com/project/lincoln-center-hypar?index=false&section=projects&search=lincoln",
    "image": "https://cdn.sanity.io/images/q2tdbkqz/production/VB9MvueucrFggi4owEQ46nM1-2200x1439.jpg?w=1500&fit=max&q=90"
  },
  {
    "id": "market-hall-aarau",
    "title": "Market Hall, Aarau",
    "type": "Building",
    "year": null,
    "designer": "Miller & Maranta, Ruedi Walti",
    "location": "Aarau, Switzerland",
    "lat": 47.3925,
    "lng": 8.0443,
    "url": "",
    "image": ""
  },
  {
    "id": "the-temporary-market-hall",
    "title": "The Temporary Market Hall",
    "type": "Building",
    "year": null,
    "designer": "Tengbom, Felix Lerbach",
    "location": "Stockholm, Sweden",
    "lat": 59.335,
    "lng": 18.078,
    "url": "",
    "image": ""
  },
  {
    "id": "kibi-kogen-n-square",
    "title": "Kibi Kogen N Square",
    "type": "Building",
    "year": null,
    "designer": "Kengo Kuma",
    "location": "Kibichuo, Okayama, Japan",
    "lat": 34.8,
    "lng": 133.73,
    "url": "",
    "image": ""
  },
  {
    "id": "tamedia-new-office-building-2013",
    "title": "Tamedia New Office Building",
    "type": "Building",
    "year": 2013,
    "designer": "Shigeru Ban",
    "location": "Zurich, Switzerland",
    "lat": 47.3736,
    "lng": 8.5272,
    "url": "",
    "image": ""
  },
  {
    "id": "mannheim-multihalle-1975",
    "title": "Mannheim Multihalle",
    "type": "Building",
    "year": 1975,
    "designer": "Frei Otto",
    "location": "Mannheim, Germany",
    "lat": 49.509,
    "lng": 8.472,
    "url": "https://mannheim-multihalle.de/en/architecture/",
    "image": ""
  },
  {
    "id": "metropol-parasol-2011",
    "title": "Metropol Parasol",
    "type": "Building",
    "year": 2011,
    "designer": "J. Mayer H.",
    "location": "Seville, Spain",
    "lat": 37.3932,
    "lng": -5.9916,
    "url": "",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRD3OAct13EpD7oiqdzoLBA2PUDAcqfyvPUbFhKLTlyqoPYGm2w5Rii-zFc&s=10"
  },
  {
    "id": "asahi-kindergarten-phase-ii",
    "title": "Asahi Kindergarten Phase II",
    "type": "Building",
    "year": null,
    "designer": "Tezuka Architects",
    "location": "",
    "url": "",
    "image": ""
  },
  {
    "id": "timber-bridge-in-gulou",
    "title": "Timber Bridge in Gulou",
    "type": "Building",
    "year": null,
    "designer": "LUO studio, Jin Weiqi",
    "location": "Jiangmen, China",
    "lat": 22.579,
    "lng": 113.082,
    "url": "",
    "image": ""
  },
  {
    "id": "viikki-church-2005",
    "title": "Viikki Church",
    "type": "Building",
    "year": 2005,
    "designer": "JKMM",
    "location": "Helsinki, Finland",
    "lat": 60.2268,
    "lng": 25.019,
    "url": "",
    "image": ""
  },
  {
    "id": "husaro",
    "title": "Husarö",
    "type": "Building",
    "year": null,
    "designer": "Tham & Videgård",
    "location": "Husarö, Sweden",
    "lat": 59.64,
    "lng": 18.99,
    "url": "",
    "image": ""
  },
  {
    "id": "groupe-scolaire-pasteur-2013",
    "title": "Groupe Scolaire Pasteur",
    "type": "Building",
    "year": 2013,
    "designer": "R2K Architectes",
    "location": "Grenoble, France",
    "lat": 45.1885,
    "lng": 5.7245,
    "url": "",
    "image": ""
  },
  {
    "id": "archery-hall",
    "title": "Archery Hall",
    "type": "Building",
    "year": 2013,
    "designer": "FT Architects",
    "location": "Tokyo, Japan",
    "lat": 35.67686,
    "lng": 139.76389,
    "url": "https://divisare.com/projects/337658-ft-architects-shigeo-ogawa-boxing-club",
    "image": "https://images.divisare.com//images/f_auto,q_auto,w_800/v1487243915/fklqtww2lhnjtaqzodoy/ft-architects-shigeo-ogawa-boxing-club.jpg"
  },
  {
    "id": "boxing-club",
    "title": "Boxing Club",
    "type": "Building",
    "year": 2013,
    "designer": "FT Architects",
    "location": "Tokyo, Japan",
    "lat": 35.67686,
    "lng": 139.76389,
    "url": "https://divisare.com/projects/336478-ft-architects-shigeo-ogawa-archery-hall",
    "image": "https://images.divisare.com//images/f_auto,q_auto,w_800/v1486036720/nxodoalsez4d19ioikfi/ft-architects-shigeo-ogawa-archery-hall.jpg"
  },
  {
    "id": "karsamaki-shingle-church-2004",
    "title": "Kärsämäki Shingle Church",
    "type": "Building",
    "year": 2004,
    "designer": "OOPEAA",
    "location": "Kärsämäki, Finland",
    "lat": 63.9667,
    "lng": 25.7667,
    "url": "",
    "image": ""
  },
  {
    "id": "otaniemi-chapel-1957",
    "title": "Otaniemi Chapel",
    "type": "Building",
    "year": 1957,
    "designer": "Heikki and Kaija Siren",
    "location": "Espoo, Finland",
    "lat": 60.185,
    "lng": 24.8235,
    "url": "https://divisare.com/projects/329795-heikki-and-kaija-siren-federico-covre-otaniemi-chapel",
    "image": "https://images.divisare.com//images/f_auto,q_auto,w_800/v1478339673/yhdbxyzhjnrjimb3ak1d/heikki-and-kaija-siren-federico-covre-otaniemi-chapel.jpg"
  },
  {
    "id": "gehry-house-1978",
    "title": "Gehry House",
    "type": "Building",
    "year": 1978,
    "designer": "Frank Gehry",
    "location": "Santa Monica, CA, USA",
    "lat": 34.0236,
    "lng": -118.4851,
    "url": "https://hicarquitectura.com/2025/12/frank-gehry-house-gehry/",
    "image": "https://hicarquitectura.com/wp-content/uploads/2022/12/vaumm_7.jpg"
  },
  {
    "id": "helio-olga-house-1990",
    "title": "Hélio Olga House",
    "type": "Building",
    "year": 1990,
    "designer": "Marcos Acayaba",
    "location": "São Paulo, Brazil",
    "lat": -23.5505,
    "lng": -46.6333,
    "url": "https://ofhouses.com/post/96778979900/073-marcos-acayaba-h%C3%A9lio-olga-de-souza-jr",
    "image": "https://64.media.tumblr.com/fca2e0eaceddc07ce2cffe476cc26d1f/tumblr_nbh9y4vVel1twhq1io2_640.jpg"
  },
  {
    "id": "shade-pavilion",
    "title": "Shade Pavilion",
    "type": "Building",
    "year": null,
    "designer": "Liz Gálvez",
    "location": "Los Angeles, CA, USA",
    "lat": 34.0522,
    "lng": -118.2437,
    "url": "",
    "image": ""
  },
  {
    "id": "arch-7010",
    "title": "ARCH 7010",
    "type": "",
    "year": null,
    "designer": "Klein | Weitzman",
    "location": "",
    "url": "",
    "image": ""
  },
  {
    "id": "camera-obscura-2015",
    "title": "Camera Obscura",
    "type": "Building",
    "year": 2015,
    "designer": "Mariano Dallago",
    "location": "San Martino in Badia, Italy",
    "lat": 46.7019,
    "lng": 11.8939,
    "url": "",
    "image": ""
  },
  {
    "id": "royal-academy-of-arts-2019",
    "title": "Royal Academy of Arts",
    "type": "Sculpture",
    "year": 2019,
    "designer": "Giles Retsin",
    "location": "London, UK",
    "lat": 51.50745,
    "lng": -0.12777,
    "url": "https://www.retsin.org/Royal-Academy-of-Arts",
    "image": "https://payload.cargocollective.com/1/14/468850/13806736/Gilles-Retsin-Royal-Academy-Drawing-1-Reflected-Ceiling-_670.jpg"
  },
  {
    "id": "the-turned-room-2023",
    "title": "The Turned Room",
    "type": "Drawing",
    "year": 2023,
    "designer": "Young & Ayata",
    "location": "",
    "url": "https://www.young-ayata.com/the-turned-room",
    "image": "https://images.squarespace-cdn.com/content/v1/53d133fee4b088cc18049660/1701356306942-37GMGFKI339DWZZ425LO/Young%2B%26%2BAyata%2B-%2BThe%2BTurned%2BRoom%2B8.jpg?format=2500w"
  },
  {
    "id": "450-warren-2022",
    "title": "450 Warren",
    "type": "Building",
    "year": 2022,
    "designer": "",
    "location": "450 Warren, Brooklyn, New York",
    "lat": 40.68343,
    "lng": -73.98685,
    "url": "https://solidobjectives.com/work/450-warren/",
    "image": "https://images.ctfassets.net/6v3ra0uy9tu9/4XwsjBE7TCDn2m0ahnWCnU/28e6de9bc314de52e77b7800891766a6/450_Warren_SO-IL_3815.jpg?w=1920&h=1282&q=80&fm=webp"
  },
  {
    "id": "sandwiches-2016",
    "title": "Sandwiches",
    "type": "Hypothetical",
    "year": 2016,
    "designer": "Jennifer Bonner",
    "location": "",
    "url": "https://jenniferbonner.com/06-Best-Sandwiches",
    "image": "https://freight.cargo.site/w/750/i/5c85b8994d1fb4d3294e2170d910d0118de0e14d5d4f39121e7d0c061778e9e8/MALL_BestSandwiches_Render-2.jpg"
  }
];
